# Intro to PyTorch

### Setting it up
Installation: Visit https://pytorch.org/ and Navigate to Quick Start <br>
Tutorials: https://pytorch.org/tutorials/

## PyTorch
A python package that provides:
- Tensor computation (like numpy) with strong GPU acceleration
- Deep Neural Networks built on autodiff system

In [2]:
import torch
print(torch.__version__)

1.3.0+cpu


### Important Packages
![alt text](images/torch-pkg.png)

### Tensor

Nd Arrays<br>
![alt text](images/tensors.png)

In [3]:
a = torch.tensor([[1,2.0],[3,4]])
print(a)
print(a.size())
print(a.dtype)

tensor([[1., 2.],
        [3., 4.]])
torch.Size([2, 2])
torch.float32


In [4]:
a = torch.rand((3,4))
print(a)

tensor([[0.3566, 0.9426, 0.9052, 0.1622],
        [0.4921, 0.1280, 0.1739, 0.5581],
        [0.5677, 0.4948, 0.2131, 0.6420]])


### Numpy Bridge

In [5]:
import numpy as np

#Numpy to Torch
a = np.random.random((3,3))
print(a)
b = torch.from_numpy(a)
print(b)

#Torch to Numpy
c = b.numpy()
print(c)

[[0.91055163 0.14150936 0.32507186]
 [0.35591266 0.51754281 0.27518454]
 [0.43848364 0.37824601 0.14053193]]
tensor([[0.9106, 0.1415, 0.3251],
        [0.3559, 0.5175, 0.2752],
        [0.4385, 0.3782, 0.1405]], dtype=torch.float64)
[[0.91055163 0.14150936 0.32507186]
 [0.35591266 0.51754281 0.27518454]
 [0.43848364 0.37824601 0.14053193]]


### CUDA Tensors

In [6]:
torch.cuda.is_available()

False

In [7]:
a = torch.rand(3,3)
if torch.cuda.is_available():
    device = torch.device("cuda")
    a = a.to(device)
    # or #
    b = torch.rand(3,3, device=device)
    
    c = a + b
    print(c)
    # or #
    print(c.to("cpu"))

### Autograd Mechanics
Autograd package provide the automatic differentiation capability to all operations on tensor. It is a define-by-run framework, which means that your backprop is defined by how your code is run, and that every single iteration can be different.

In [8]:
a = torch.rand(3,3)
print(a.requires_grad)

False


In [9]:
#Start tracking all operations on the tensor
a.requires_grad = True
print(a.requires_grad)

a = torch.rand((3,3),requires_grad=True)
print(a)
print(a.grad)

True
tensor([[0.1065, 0.1034, 0.1755],
        [0.9275, 0.8035, 0.6220],
        [0.6818, 0.1374, 0.4339]], requires_grad=True)
None


#### Computational Graph (DAG)

Let's take an example:<br><br>
$y = x + 2$ <br>
$z = 3y^2$<br>
$o = \frac{1}{4}\sum_i z_i$<br>

Let $x=
\begin{bmatrix}
2 & 2\\
2 & 2
\end{bmatrix}$

In [9]:
x = torch.tensor([[2.0, 2.0],[2.0, 2.0]], requires_grad=True)
print(x)

y = x + 2
print(y)

z = y * y * 3

out = z.mean()

print(z, out)

tensor([[2., 2.],
        [2., 2.]], requires_grad=True)
tensor([[4., 4.],
        [4., 4.]], grad_fn=<AddBackward>)
tensor([[48., 48.],
        [48., 48.]], grad_fn=<MulBackward>) tensor(48., grad_fn=<MeanBackward1>)


In [10]:
z.requires_grad

True

In [11]:
#back prop
out.backward()

In [12]:
print(x.grad)

tensor([[6., 6.],
        [6., 6.]])
